name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .

      - name: Run tests
        run: npm test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            tests/**/*.test.js
            coverage/

  deploy_qa:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-report

      - name: Deploy to QA
        run: echo "Deploying to QA environment..."

  deploy_prod:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-report

      - name: Deploy to Production
        run: echo "Deploying to Production environment..."
