name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  # 1️⃣ CI job: lint + test + create artifact
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Create artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: ciproject-artifact
          path: |
            tests/
            package.json
            package-lock.json

  # 2️⃣ QA Deploy (only dev branch)
  deploy_qa:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ciproject-artifact

      - name: Simulate QA deployment
        run: echo "Deploying to QA environment"

  # 3️⃣ Production Deploy (only main branch)
  deploy_prod:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ciproject-artifact

      - name: Simulate Production deployment
        run: echo "Deploying to Production environment"
