name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    name: Run Lint & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint || echo "⚠️ No lint script found"

      - name: Run Tests
        run: npm test

      # upload tests folder as artifact (since build/ may not exist)
      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: tests/

  deploy_qa:
    name: Deploy to QA
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Simulate QA deploy
        run: echo "🚀 Deploying to QA environment..."

  deploy_prod:
    name: Deploy to Production
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Simulate Production deploy
        run: echo "🚀 Deploying to Production environment..."
